//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.Presentation.Prism.Wpf.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SkinResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkinResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.Presentation.Prism.Wpf.Resources.Strings.SkinResources", typeof(SkinResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défaut.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleu Ciel.
        /// </summary>
        internal static string azur {
            get {
                return ResourceManager.GetString("azur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleu.
        /// </summary>
        internal static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sombre.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleu foncé.
        /// </summary>
        internal static string darkblue {
            get {
                return ResourceManager.GetString("darkblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert.
        /// </summary>
        internal static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clair.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string orange {
            get {
                return ResourceManager.GetString("orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose.
        /// </summary>
        internal static string pink {
            get {
                return ResourceManager.GetString("pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string purple {
            get {
                return ResourceManager.GetString("purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouge.
        /// </summary>
        internal static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaune.
        /// </summary>
        internal static string yellow {
            get {
                return ResourceManager.GetString("yellow", resourceCulture);
            }
        }
    }
}
