//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.Presentation.Prism.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.Presentation.Prism.Resources.Strings.StatusResources", typeof(StatusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application chargée.
        /// </summary>
        public static string ApplicationEndLoading {
            get {
                return ResourceManager.GetString("ApplicationEndLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement de l&apos;application.
        /// </summary>
        public static string ApplicationStartLoading {
            get {
                return ResourceManager.GetString("ApplicationStartLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La connexion a échouée. Vérifier le nom d&apos;utilisateur et le mot de passe..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt.
        /// </summary>
        public static string DefaultStatusMessage {
            get {
                return ResourceManager.GetString("DefaultStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement du module &quot;{0}&quot;.
        /// </summary>
        public static string ModuleLoading {
            get {
                return ResourceManager.GetString("ModuleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des modules.
        /// </summary>
        public static string ModulesLoading {
            get {
                return ResourceManager.GetString("ModulesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement de l&apos;interface.
        /// </summary>
        public static string SkinLoading {
            get {
                return ResourceManager.GetString("SkinLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion réussi...
        ///Utilisateur connecté : {0}.
        /// </summary>
        public static string UserConnected {
            get {
                return ResourceManager.GetString("UserConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion de l&apos;utilisateur.
        /// </summary>
        public static string UserConnection {
            get {
                return ResourceManager.GetString("UserConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement du profil utilisateur.
        /// </summary>
        public static string UserLoading {
            get {
                return ResourceManager.GetString("UserLoading", resourceCulture);
            }
        }
    }
}
