//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.Presentation.Prism.Modules.Administration.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministrationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministrationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.Presentation.Prism.Modules.Administration.Resources.Strings.Admin" +
                            "istrationResources", typeof(AdministrationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AdministrationMenu {
            get {
                return ResourceManager.GetString("AdministrationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        public static string CategoriesMenu {
            get {
                return ResourceManager.GetString("CategoriesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des catégories.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les éducateurs.
        /// </summary>
        public static string CoachesMenu {
            get {
                return ResourceManager.GetString("CoachesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des éducateurs.
        /// </summary>
        public static string CoachesTitle {
            get {
                return ResourceManager.GetString("CoachesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateurs.
        /// </summary>
        public static string CoachTitle {
            get {
                return ResourceManager.GetString("CoachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les joueurs.
        /// </summary>
        public static string PlayersMenu {
            get {
                return ResourceManager.GetString("PlayersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des joueurs.
        /// </summary>
        public static string PlayersTitle {
            get {
                return ResourceManager.GetString("PlayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueur.
        /// </summary>
        public static string PlayerTitle {
            get {
                return ResourceManager.GetString("PlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postes.
        /// </summary>
        public static string PositionsMenu {
            get {
                return ResourceManager.GetString("PositionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des postes.
        /// </summary>
        public static string PositionsTitle {
            get {
                return ResourceManager.GetString("PositionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste.
        /// </summary>
        public static string PositionTitle {
            get {
                return ResourceManager.GetString("PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisons.
        /// </summary>
        public static string SeasonsMenu {
            get {
                return ResourceManager.GetString("SeasonsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des saisons.
        /// </summary>
        public static string SeasonsTitle {
            get {
                return ResourceManager.GetString("SeasonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saison.
        /// </summary>
        public static string SeasonTitle {
            get {
                return ResourceManager.GetString("SeasonTitle", resourceCulture);
            }
        }
    }
}
