//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toute.
        /// </summary>
        public static string AllFemale {
            get {
                return ResourceManager.GetString("AllFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes.
        /// </summary>
        public static string AllFemales {
            get {
                return ResourceManager.GetString("AllFemales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout.
        /// </summary>
        public static string AllMale {
            get {
                return ResourceManager.GetString("AllMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string AllMales {
            get {
                return ResourceManager.GetString("AllMales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        public static string From1 {
            get {
                return ResourceManager.GetString("From1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est entre.
        /// </summary>
        public static string IsBetween {
            get {
                return ResourceManager.GetString("IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun(e).
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string NoneFemale {
            get {
                return ResourceManager.GetString("NoneFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string NoneMale {
            get {
                return ResourceManager.GetString("NoneMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au.
        /// </summary>
        public static string To1 {
            get {
                return ResourceManager.GetString("To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non défini(e).
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non définie.
        /// </summary>
        public static string UndefinedFemale {
            get {
                return ResourceManager.GetString("UndefinedFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non défini.
        /// </summary>
        public static string UndefinedMale {
            get {
                return ResourceManager.GetString("UndefinedMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non définies.
        /// </summary>
        public static string UndefinedPluralFemale {
            get {
                return ResourceManager.GetString("UndefinedPluralFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non défini(e)s.
        /// </summary>
        public static string UndefiniedPlural {
            get {
                return ResourceManager.GetString("UndefiniedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non définis.
        /// </summary>
        public static string UndefiniedPluralMale {
            get {
                return ResourceManager.GetString("UndefiniedPluralMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu(e).
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnue.
        /// </summary>
        public static string UnknownFemale {
            get {
                return ResourceManager.GetString("UnknownFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string UnknownMale {
            get {
                return ResourceManager.GetString("UnknownMale", resourceCulture);
            }
        }
    }
}
