//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application chargée.
        /// </summary>
        public static string ApplicationEndLoading {
            get {
                return ResourceManager.GetString("ApplicationEndLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement de l&apos;application.
        /// </summary>
        public static string ApplicationStartLoading {
            get {
                return ResourceManager.GetString("ApplicationStartLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En quittant la page, vous perdrez toutes les modifications non sauvegardées. Voulez-vous continuer ?.
        /// </summary>
        public static string CancelModifications {
            get {
                return ResourceManager.GetString("CancelModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de supprimer définitivement un élément de l&apos;application. Voulez-vous continuez ?.
        /// </summary>
        public static string ConfirmationRemovingItem {
            get {
                return ResourceManager.GetString("ConfirmationRemovingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de supprimer définitivement le(s) élément(s) sélectionné(s) de l&apos;application. Voulez-vous continuez ?.
        /// </summary>
        public static string ConfirmationRemovingItems {
            get {
                return ResourceManager.GetString("ConfirmationRemovingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La connexion a échouée. Vérifier le nom d&apos;utilisateur et le mot de passe..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la récupération des données. Veuillez contacter l&apos;administrateur..
        /// </summary>
        public static string GetDataError {
            get {
                return ResourceManager.GetString("GetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} élément(s) ont été ajouté(s).
        /// </summary>
        public static string ItemsAdded {
            get {
                return ResourceManager.GetString("ItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des données....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement du module &quot;{0}&quot;.
        /// </summary>
        public static string ModuleLoading {
            get {
                return ResourceManager.GetString("ModuleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des modules.
        /// </summary>
        public static string ModulesLoading {
            get {
                return ResourceManager.GetString("ModulesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ont été déplacés en {1} avec succès..
        /// </summary>
        public static string MovingPlayersToSquad {
            get {
                return ResourceManager.GetString("MovingPlayersToSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a été déplacé en {1} avec succès..
        /// </summary>
        public static string MovingPlayerToSquad {
            get {
                return ResourceManager.GetString("MovingPlayerToSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ordre d&apos;affichage des éléments a bien été sauvegardé..
        /// </summary>
        public static string OrderSaved {
            get {
                return ResourceManager.GetString("OrderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prêt.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Des changements ont été effectués. L&apos;application va redémarrer..
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;élément a bien été sauvegardé..
        /// </summary>
        public static string SavingSuccess {
            get {
                return ResourceManager.GetString("SavingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement de l&apos;interface.
        /// </summary>
        public static string SkinLoading {
            get {
                return ResourceManager.GetString("SkinLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion réussi...
        ///Utilisateur connecté : {0}.
        /// </summary>
        public static string UserConnected {
            get {
                return ResourceManager.GetString("UserConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion de l&apos;utilisateur.
        /// </summary>
        public static string UserConnection {
            get {
                return ResourceManager.GetString("UserConnection", resourceCulture);
            }
        }
    }
}
