//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès refusé. Vous n&apos;avez pas les droits pour accéder à l&apos;application..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouverture de l&apos;application....
        /// </summary>
        public static string AppOpening {
            get {
                return ResourceManager.GetString("AppOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En quittant la page, vous perdrez toutes les modifications non sauvegardées. Voulez-vous continuer ?.
        /// </summary>
        public static string CancelModifications {
            get {
                return ResourceManager.GetString("CancelModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de supprimer définitivement un élément de l&apos;application. Voulez-vous continuez ?.
        /// </summary>
        public static string ConfirmationRemovingItem {
            get {
                return ResourceManager.GetString("ConfirmationRemovingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La connexion a échouée. Vérifier le nom d&apos;utilisateur et le mot de passe..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion réussie....
        /// </summary>
        public static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Création.
        /// </summary>
        public static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Edition.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue. L&apos;application va se fermer. Veuillez contacter l&apos;administrateur..
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la récupération des données. Veuillez contacter l&apos;administrateur..
        /// </summary>
        public static string GetDataError {
            get {
                return ResourceManager.GetString("GetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de sauvegarder. Veuillez vérifier les valeurs des champs renseignés..
        /// </summary>
        public static string InvalidForm {
            get {
                return ResourceManager.GetString("InvalidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des données....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;êtes pas connecté à l&apos;application..
        /// </summary>
        public static string NotLogged {
            get {
                return ResourceManager.GetString("NotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ordre d&apos;affichage des éléments a bien été sauvegardé..
        /// </summary>
        public static string OrderSaved {
            get {
                return ResourceManager.GetString("OrderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suppression a échouée..
        /// </summary>
        public static string RemovingFailed {
            get {
                return ResourceManager.GetString("RemovingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sauvegarde a échouée. Veuillez contacter l&apos;administrateur..
        /// </summary>
        public static string SavingFailed {
            get {
                return ResourceManager.GetString("SavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;élément a bien été sauvegardé..
        /// </summary>
        public static string SavingSuccess {
            get {
                return ResourceManager.GetString("SavingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion de l&apos;utilsateur....
        /// </summary>
        public static string UserConnection {
            get {
                return ResourceManager.GetString("UserConnection", resourceCulture);
            }
        }
    }
}
