//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.ValidationMessageResources", typeof(ValidationMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;élément &quot;{0}&quot; existe déjà..
        /// </summary>
        public static string AlreadyExistMessage {
            get {
                return ResourceManager.GetString("AlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;Code&quot; est requis..
        /// </summary>
        public static string CodeIsRequiredMessage {
            get {
                return ResourceManager.GetString("CodeIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format ne correspond pas à une adresse mail..
        /// </summary>
        public static string EmailFormatMessage {
            get {
                return ResourceManager.GetString("EmailFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurs lors de la sauvegarde de l&apos;entité de type &quot;{0}&quot; : .
        /// </summary>
        public static string EntityErrorHeader {
            get {
                return ResourceManager.GetString("EntityErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce champ est obligatoire..
        /// </summary>
        public static string IsRequiredFieldMessage {
            get {
                return ResourceManager.GetString("IsRequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;élément &quot;{0}&quot; est utilisée par d&apos;autres entités..
        /// </summary>
        public static string IsUsedMessage {
            get {
                return ResourceManager.GetString("IsUsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;Label&quot; est requis..
        /// </summary>
        public static string LabelIsRequiredMessage {
            get {
                return ResourceManager.GetString("LabelIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string MaxLenghtFieldMessage {
            get {
                return ResourceManager.GetString("MaxLenghtFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données ne sont pas valides..
        /// </summary>
        public static string NotValidMessage {
            get {
                return ResourceManager.GetString("NotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format ne correspond pas à un numéro de téléphone..
        /// </summary>
        public static string PhoneFormatMessage {
            get {
                return ResourceManager.GetString("PhoneFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être compris entre {1} et {2}.
        /// </summary>
        public static string RangeFieldMessage {
            get {
                return ResourceManager.GetString("RangeFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre d&apos;éléments doit être supérieur ou égal à 0..
        /// </summary>
        public static string RepositoryPageCountArgumentException {
            get {
                return ResourceManager.GetString("RepositoryPageCountArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de page doit être supérieur ou égal à 0..
        /// </summary>
        public static string RepositoryPageIndexArgumentException {
            get {
                return ResourceManager.GetString("RepositoryPageIndexArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; est requis..
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
    }
}
