//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessageResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.ValidationMessageResources", typeof(ValidationMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;élément &quot;{0}&quot; existe déjà..
        /// </summary>
        public static string AlreadyExistMessage {
            get {
                return ResourceManager.GetString("AlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format ne correspond pas à une adresse mail..
        /// </summary>
        public static string EmailFormatMessage {
            get {
                return ResourceManager.GetString("EmailFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreurs lors de la sauvegarde de l&apos;entité de type &quot;{0}&quot; : .
        /// </summary>
        public static string EntityErrorHeader {
            get {
                return ResourceManager.GetString("EntityErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs renseignés ne sont pas corrects..
        /// </summary>
        public static string InvalidFields {
            get {
                return ResourceManager.GetString("InvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est obligatoire..
        /// </summary>
        public static string IsRequiredFieldMessage {
            get {
                return ResourceManager.GetString("IsRequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;élément &quot;{0}&quot; est utilisée par d&apos;autres entités..
        /// </summary>
        public static string IsUsedMessage {
            get {
                return ResourceManager.GetString("IsUsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ &quot;{0}&quot; ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string MaxLenghtFieldMessage {
            get {
                return ResourceManager.GetString("MaxLenghtFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format ne correspond pas à un numéro de téléphone..
        /// </summary>
        public static string PhoneFormatMessage {
            get {
                return ResourceManager.GetString("PhoneFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ &quot;{0}&quot; doit être compris entre {1} et {2}.
        /// </summary>
        public static string RangeFieldMessage {
            get {
                return ResourceManager.GetString("RangeFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre d&apos;éléments doit être supérieur ou égal à 0..
        /// </summary>
        public static string RepositoryPageCountArgumentException {
            get {
                return ResourceManager.GetString("RepositoryPageCountArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de page doit être supérieur ou égal à 0..
        /// </summary>
        public static string RepositoryPageIndexArgumentException {
            get {
                return ResourceManager.GetString("RepositoryPageIndexArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ &quot;{0}&quot; est requis..
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de début doit être inférieure à la date de fin..
        /// </summary>
        public static string StartDateLessThanEndDateMessage {
            get {
                return ResourceManager.GetString("StartDateLessThanEndDateMessage", resourceCulture);
            }
        }
    }
}
