//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InjuryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InjuryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.Entities.InjuryResources", typeof(InjuryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résumé.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pubalgie.
        /// </summary>
        public static string DefaultInjuryBack {
            get {
                return ResourceManager.GetString("DefaultInjuryBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contusion à la tête.
        /// </summary>
        public static string DefaultInjuryHead {
            get {
                return ResourceManager.GetString("DefaultInjuryHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse de la cheville gauche.
        /// </summary>
        public static string DefaultInjuryLeftAnkle {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du bras gauche.
        /// </summary>
        public static string DefaultInjuryLeftArm {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du coude gauche.
        /// </summary>
        public static string DefaultInjuryLeftElbow {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du pied gauche.
        /// </summary>
        public static string DefaultInjuryLeftFoot {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contusion à la main gauche.
        /// </summary>
        public static string DefaultInjuryLeftHand {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du genou gauche.
        /// </summary>
        public static string DefaultInjuryLeftKnee {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du tibia gauche.
        /// </summary>
        public static string DefaultInjuryLeftShin {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxation de l&apos;épaule gauche.
        /// </summary>
        public static string DefaultInjuryLeftShoulder {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déchirure à la cuisse gauche.
        /// </summary>
        public static string DefaultInjuryLeftThigh {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du poignet gauche.
        /// </summary>
        public static string DefaultInjuryLeftWrist {
            get {
                return ResourceManager.GetString("DefaultInjuryLeftWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douleurs aux cervicales.
        /// </summary>
        public static string DefaultInjuryNeck {
            get {
                return ResourceManager.GetString("DefaultInjuryNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse de la cheville droite.
        /// </summary>
        public static string DefaultInjuryRightAnkle {
            get {
                return ResourceManager.GetString("DefaultInjuryRightAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du bras droit.
        /// </summary>
        public static string DefaultInjuryRightArm {
            get {
                return ResourceManager.GetString("DefaultInjuryRightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du coude droit.
        /// </summary>
        public static string DefaultInjuryRightElbow {
            get {
                return ResourceManager.GetString("DefaultInjuryRightElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du pied droit.
        /// </summary>
        public static string DefaultInjuryRightFoot {
            get {
                return ResourceManager.GetString("DefaultInjuryRightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contusion à la main droite.
        /// </summary>
        public static string DefaultInjuryRightHand {
            get {
                return ResourceManager.GetString("DefaultInjuryRightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du genou droit.
        /// </summary>
        public static string DefaultInjuryRightKnee {
            get {
                return ResourceManager.GetString("DefaultInjuryRightKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fracture du tibia droit.
        /// </summary>
        public static string DefaultInjuryRightShin {
            get {
                return ResourceManager.GetString("DefaultInjuryRightShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxation de l&apos;épaule droite.
        /// </summary>
        public static string DefaultInjuryRightShoulder {
            get {
                return ResourceManager.GetString("DefaultInjuryRightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déchirure à la cuisse droite.
        /// </summary>
        public static string DefaultInjuryRightThigh {
            get {
                return ResourceManager.GetString("DefaultInjuryRightThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorse du poignet droit.
        /// </summary>
        public static string DefaultInjuryRightWrist {
            get {
                return ResourceManager.GetString("DefaultInjuryRightWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal au ventre.
        /// </summary>
        public static string DefaultInjuryStomach {
            get {
                return ResourceManager.GetString("DefaultInjuryStomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Côtes fracturées.
        /// </summary>
        public static string DefaultInjuryTorso {
            get {
                return ResourceManager.GetString("DefaultInjuryTorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de retour.
        /// </summary>
        public static string ExpectedReturn {
            get {
                return ResourceManager.GetString("ExpectedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jour(s).
        /// </summary>
        public static string ExpectedReturnInDays {
            get {
                return ResourceManager.GetString("ExpectedReturnInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mois.
        /// </summary>
        public static string ExpectedReturnInMonth {
            get {
                return ResourceManager.GetString("ExpectedReturnInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} semaine(s).
        /// </summary>
        public static string ExpectedReturnInWeeks {
            get {
                return ResourceManager.GetString("ExpectedReturnInWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sévérité.
        /// </summary>
        public static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
