//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.CoachManager.CrossCutting.Core.Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InjuryTypeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InjuryTypeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.CoachManager.CrossCutting.Core.Resources.Enums.InjuryTypeResources", typeof(InjuryTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dos.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tête.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheville gauche.
        /// </summary>
        public static string LeftAnkle {
            get {
                return ResourceManager.GetString("LeftAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bras gauche.
        /// </summary>
        public static string LeftArm {
            get {
                return ResourceManager.GetString("LeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coude gauche.
        /// </summary>
        public static string LeftElbow {
            get {
                return ResourceManager.GetString("LeftElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pied gauche.
        /// </summary>
        public static string LeftFoot {
            get {
                return ResourceManager.GetString("LeftFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main gauche.
        /// </summary>
        public static string LeftHand {
            get {
                return ResourceManager.GetString("LeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genou gauche.
        /// </summary>
        public static string LeftKnee {
            get {
                return ResourceManager.GetString("LeftKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia gauche.
        /// </summary>
        public static string LeftShin {
            get {
                return ResourceManager.GetString("LeftShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epaule gauche.
        /// </summary>
        public static string LeftShoulder {
            get {
                return ResourceManager.GetString("LeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisse gauche.
        /// </summary>
        public static string LeftThigh {
            get {
                return ResourceManager.GetString("LeftThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poignet gauche.
        /// </summary>
        public static string LeftWrist {
            get {
                return ResourceManager.GetString("LeftWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cou.
        /// </summary>
        public static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheville droite.
        /// </summary>
        public static string RightAnkle {
            get {
                return ResourceManager.GetString("RightAnkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bras droit.
        /// </summary>
        public static string RightArm {
            get {
                return ResourceManager.GetString("RightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coude droit.
        /// </summary>
        public static string RightElbow {
            get {
                return ResourceManager.GetString("RightElbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pied droit.
        /// </summary>
        public static string RightFoot {
            get {
                return ResourceManager.GetString("RightFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main droite.
        /// </summary>
        public static string RightHand {
            get {
                return ResourceManager.GetString("RightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genou droit.
        /// </summary>
        public static string RightKnee {
            get {
                return ResourceManager.GetString("RightKnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia droit.
        /// </summary>
        public static string RightShin {
            get {
                return ResourceManager.GetString("RightShin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epaule droite.
        /// </summary>
        public static string RightShoulder {
            get {
                return ResourceManager.GetString("RightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisse droite.
        /// </summary>
        public static string RightThigh {
            get {
                return ResourceManager.GetString("RightThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poignet droit.
        /// </summary>
        public static string RightWrist {
            get {
                return ResourceManager.GetString("RightWrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen.
        /// </summary>
        public static string Stomach {
            get {
                return ResourceManager.GetString("Stomach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torse.
        /// </summary>
        public static string Torso {
            get {
                return ResourceManager.GetString("Torso", resourceCulture);
            }
        }
    }
}
